// Generated by psc version 0.6.2
var PS = PS || {};
PS.Prelude = (function () {
    "use strict";
    var Unit = {
        create: function (value) {
            return value;
        }
    };
    function LT() {

    };
    LT.value = new LT();
    function GT() {

    };
    GT.value = new GT();
    function EQ() {

    };
    EQ.value = new EQ();
    function Semigroupoid($less$less$less) {
        this["<<<"] = $less$less$less;
    };
    function Category(__superclass_Prelude$dotSemigroupoid_0, id) {
        this["__superclass_Prelude.Semigroupoid_0"] = __superclass_Prelude$dotSemigroupoid_0;
        this.id = id;
    };
    function Functor($less$dollar$greater) {
        this["<$>"] = $less$dollar$greater;
    };
    function Apply($less$times$greater, __superclass_Prelude$dotFunctor_0) {
        this["<*>"] = $less$times$greater;
        this["__superclass_Prelude.Functor_0"] = __superclass_Prelude$dotFunctor_0;
    };
    function Applicative(__superclass_Prelude$dotApply_0, pure) {
        this["__superclass_Prelude.Apply_0"] = __superclass_Prelude$dotApply_0;
        this.pure = pure;
    };
    function Bind($greater$greater$eq, __superclass_Prelude$dotApply_0) {
        this[">>="] = $greater$greater$eq;
        this["__superclass_Prelude.Apply_0"] = __superclass_Prelude$dotApply_0;
    };
    function Monad(__superclass_Prelude$dotApplicative_0, __superclass_Prelude$dotBind_1) {
        this["__superclass_Prelude.Applicative_0"] = __superclass_Prelude$dotApplicative_0;
        this["__superclass_Prelude.Bind_1"] = __superclass_Prelude$dotBind_1;
    };
    function Num($percent, $times, $plus, $minus, $div, negate) {
        this["%"] = $percent;
        this["*"] = $times;
        this["+"] = $plus;
        this["-"] = $minus;
        this["/"] = $div;
        this.negate = negate;
    };
    function Eq($div$eq, $eq$eq) {
        this["/="] = $div$eq;
        this["=="] = $eq$eq;
    };
    function Ord(__superclass_Prelude$dotEq_0, compare) {
        this["__superclass_Prelude.Eq_0"] = __superclass_Prelude$dotEq_0;
        this.compare = compare;
    };
    function Bits($dot$amp$dot, $dot$up$dot, $dot$bar$dot, complement, shl, shr, zshr) {
        this[".&."] = $dot$amp$dot;
        this[".^."] = $dot$up$dot;
        this[".|."] = $dot$bar$dot;
        this.complement = complement;
        this.shl = shl;
        this.shr = shr;
        this.zshr = zshr;
    };
    function BoolLike($amp$amp, not, $bar$bar) {
        this["&&"] = $amp$amp;
        this.not = not;
        this["||"] = $bar$bar;
    };
    function cons(e) {  return function(l) {    return [e].concat(l);  };};
    function numAdd(n1) {  return function(n2) {    return n1 + n2;  };};
    function numSub(n1) {  return function(n2) {    return n1 - n2;  };};
    function numMul(n1) {  return function(n2) {    return n1 * n2;  };};
    function numDiv(n1) {  return function(n2) {    return n1 / n2;  };};
    function numMod(n1) {  return function(n2) {    return n1 % n2;  };};
    function numNegate(n) {  return -n;};
    function refEq(r1) {  return function(r2) {    return r1 === r2;  };};
    function refIneq(r1) {  return function(r2) {    return r1 !== r2;  };};
    function unsafeCompareImpl(lt) {  return function(eq) {    return function(gt) {      return function(x) {        return function(y) {          return x < y ? lt : x > y ? gt : eq;        };      };    };  };};
    function numShl(n1) {  return function(n2) {    return n1 << n2;  };};
    function numShr(n1) {  return function(n2) {    return n1 >> n2;  };};
    function numZshr(n1) {  return function(n2) {    return n1 >>> n2;  };};
    function numAnd(n1) {  return function(n2) {    return n1 & n2;  };};
    function numOr(n1) {  return function(n2) {    return n1 | n2;  };};
    function numXor(n1) {  return function(n2) {    return n1 ^ n2;  };};
    function numComplement(n) {  return ~n;};
    function boolAnd(b1) {  return function(b2) {    return b1 && b2;  };};
    function boolOr(b1) {  return function(b2) {    return b1 || b2;  };};
    function boolNot(b) {  return !b;};
    var $bar$bar = function (dict) {
        return dict["||"];
    };
    var $greater$greater$eq = function (dict) {
        return dict[">>="];
    };
    var $eq$eq = function (dict) {
        return dict["=="];
    };
    var $less$greater = function (dict) {
        return dict["<>"];
    };
    var $less$less$less = function (dict) {
        return dict["<<<"];
    };
    var $less$times$greater = function (dict) {
        return dict["<*>"];
    };
    var $colon = cons;
    var $div$eq = function (dict) {
        return dict["/="];
    };
    var $minus = function (dict) {
        return dict["-"];
    };
    var $plus = function (dict) {
        return dict["+"];
    };
    var $times = function (dict) {
        return dict["*"];
    };
    var $amp$amp = function (dict) {
        return dict["&&"];
    };
    var $dollar = function (f) {
        return function (x) {
            return f(x);
        };
    };
    var unsafeCompare = unsafeCompareImpl(LT.value)(EQ.value)(GT.value);
    var unit = {};
    var semigroupoidArr = new Semigroupoid(function (f) {
        return function (g) {
            return function (x) {
                return f(g(x));
            };
        };
    });
    var pure = function (dict) {
        return dict.pure;
    };
    var $$return = function (__dict_Monad_5) {
        return pure(__dict_Monad_5["__superclass_Prelude.Applicative_0"]());
    };
    var otherwise = true;
    var numNumber = new Num(numMod, numMul, numAdd, numSub, numDiv, numNegate);
    var not = function (dict) {
        return dict.not;
    };
    var liftA1 = function (__dict_Applicative_7) {
        return function (f) {
            return function (a) {
                return $less$times$greater(__dict_Applicative_7["__superclass_Prelude.Apply_0"]())(pure(__dict_Applicative_7)(f))(a);
            };
        };
    };
    var id = function (dict) {
        return dict.id;
    };
    var flip = function (f) {
        return function (b) {
            return function (a) {
                return f(a)(b);
            };
        };
    };
    var eqNumber = new Eq(refIneq, refEq);
    var ordNumber = new Ord(function () {
        return eqNumber;
    }, unsafeCompare);
    var $$const = function (_15) {
        return function (_16) {
            return _15;
        };
    };
    var complement = function (dict) {
        return dict.complement;
    };
    var compare = function (dict) {
        return dict.compare;
    };
    var $less = function (__dict_Ord_11) {
        return function (a1) {
            return function (a2) {
                var _353 = compare(__dict_Ord_11)(a1)(a2);
                if (_353 instanceof LT) {
                    return true;
                };
                return false;
            };
        };
    };
    var $less$eq = function (__dict_Ord_12) {
        return function (a1) {
            return function (a2) {
                var _354 = compare(__dict_Ord_12)(a1)(a2);
                if (_354 instanceof GT) {
                    return false;
                };
                return true;
            };
        };
    };
    var $greater$eq = function (__dict_Ord_14) {
        return function (a1) {
            return function (a2) {
                var _355 = compare(__dict_Ord_14)(a1)(a2);
                if (_355 instanceof LT) {
                    return false;
                };
                return true;
            };
        };
    };
    var categoryArr = new Category(function () {
        return semigroupoidArr;
    }, function (x) {
        return x;
    });
    var boolLikeBoolean = new BoolLike(boolAnd, boolNot, boolOr);
    var bitsNumber = new Bits(numAnd, numXor, numOr, numComplement, numShl, numShr, numZshr);
    var ap = function (__dict_Monad_15) {
        return function (f) {
            return function (a) {
                return $greater$greater$eq(__dict_Monad_15["__superclass_Prelude.Bind_1"]())(f)(function (_2) {
                    return $greater$greater$eq(__dict_Monad_15["__superclass_Prelude.Bind_1"]())(a)(function (_1) {
                        return $$return(__dict_Monad_15)(_2(_1));
                    });
                });
            };
        };
    };
    return {
        "$": $dollar, 
        "&&": $amp$amp, 
        "*": $times, 
        "+": $plus, 
        "-": $minus, 
        "/=": $div$eq, 
        ":": $colon, 
        "<": $less, 
        "<*>": $less$times$greater, 
        "<<<": $less$less$less, 
        "<=": $less$eq, 
        "<>": $less$greater, 
        "==": $eq$eq, 
        ">=": $greater$eq, 
        ">>=": $greater$greater$eq, 
        Applicative: Applicative, 
        Apply: Apply, 
        Bind: Bind, 
        Bits: Bits, 
        BoolLike: BoolLike, 
        Category: Category, 
        EQ: EQ, 
        Eq: Eq, 
        Functor: Functor, 
        GT: GT, 
        LT: LT, 
        Monad: Monad, 
        Num: Num, 
        Ord: Ord, 
        Semigroupoid: Semigroupoid, 
        Unit: Unit, 
        ap: ap, 
        bitsNumber: bitsNumber, 
        boolLikeBoolean: boolLikeBoolean, 
        categoryArr: categoryArr, 
        compare: compare, 
        complement: complement, 
        cons: cons, 
        "const": $$const, 
        eqNumber: eqNumber, 
        flip: flip, 
        id: id, 
        liftA1: liftA1, 
        not: not, 
        numNumber: numNumber, 
        ordNumber: ordNumber, 
        otherwise: otherwise, 
        pure: pure, 
        refEq: refEq, 
        refIneq: refIneq, 
        "return": $$return, 
        semigroupoidArr: semigroupoidArr, 
        unit: unit, 
        "||": $bar$bar
    };
})();
var PS = PS || {};
PS.Prelude_Unsafe = (function () {
    "use strict";
    var Prelude = PS.Prelude;
    function unsafeIndex(xs) {  return function(n) {    return xs[n];  };};
    return {
        unsafeIndex: unsafeIndex
    };
})();
var PS = PS || {};
PS.Math = (function () {
    "use strict";
    var Prelude = PS.Prelude;
    var floor = Math.floor;;
    return {
        floor: floor
    };
})();
var PS = PS || {};
PS.Control_Monad_Eff = (function () {
    "use strict";
    var Prelude = PS.Prelude;
    function returnE(a) {  return function() {    return a;  };};
    function bindE(a) {  return function(f) {    return function() {      return f(a())();    };  };};
    var monadEff = new Prelude.Monad(function () {
        return applicativeEff;
    }, function () {
        return bindEff;
    });
    var bindEff = new Prelude.Bind(bindE, function () {
        return applyEff;
    });
    var applyEff = new Prelude.Apply(Prelude.ap(monadEff), function () {
        return functorEff;
    });
    var applicativeEff = new Prelude.Applicative(function () {
        return applyEff;
    }, returnE);
    var functorEff = new Prelude.Functor(Prelude.liftA1(applicativeEff));
    return {
        applicativeEff: applicativeEff, 
        applyEff: applyEff, 
        bindE: bindE, 
        bindEff: bindEff, 
        functorEff: functorEff, 
        monadEff: monadEff, 
        returnE: returnE
    };
})();
var PS = PS || {};
PS.Control_Monad_Eff_Random = (function () {
    "use strict";
    var Prelude = PS.Prelude;
    function random() {  return Math.random();};
    return {
        random: random
    };
})();
var PS = PS || {};
PS.Data_Maybe = (function () {
    "use strict";
    var Prelude = PS.Prelude;
    function Nothing() {

    };
    Nothing.value = new Nothing();
    function Just(value0) {
        this.value0 = value0;
    };
    Just.create = function (value0) {
        return new Just(value0);
    };
    var maybe = function (_71) {
        return function (_72) {
            return function (_73) {
                if (_73 instanceof Nothing) {
                    return _71;
                };
                if (_73 instanceof Just) {
                    return _72(_73.value0);
                };
                throw new Error("Failed pattern match");
            };
        };
    };
    var isJust = maybe(false)(Prelude["const"](true));
    return {
        Just: Just, 
        Nothing: Nothing, 
        isJust: isJust, 
        maybe: maybe
    };
})();
var PS = PS || {};
PS.Data_Array = (function () {
    "use strict";
    var Prelude = PS.Prelude;
    var Data_Maybe = PS.Data_Maybe;
    var Prelude_Unsafe = PS.Prelude_Unsafe;
    function snoc(l) {  return function (e) {    var l1 = l.slice();    l1.push(e);     return l1;  };};
    function length (xs) {  return xs.length;};
    function concat (xss) {  var result = [];  for (var i = 0, l = xss.length; i < l; i++) {    result.push.apply(result, xss[i]);  }  return result;};
    function updateAt (index) {  return function (a) {    return function (l) {      var i = ~~index;      if (i < 0 || i >= l.length) return l;      var l1 = l.slice();      l1[i] = a;      return l1;    };   };};
    function concatMap (f) {  return function (arr) {    var result = [];    for (var i = 0, l = arr.length; i < l; i++) {      Array.prototype.push.apply(result, f(arr[i]));    }    return result;  };};
    function map (f) {  return function (arr) {    var l = arr.length;    var result = new Array(l);    for (var i = 0; i < l; i++) {      result[i] = f(arr[i]);    }    return result;  };};
    function filter (f) {  return function (arr) {    var n = 0;    var result = [];    for (var i = 0, l = arr.length; i < l; i++) {      if (f(arr[i])) {        result[n++] = arr[i];      }    }    return result;  };};
    function range (start) {  return function (end) {    var i = ~~start, e = ~~end;    var step = i > e ? -1 : 1;    var result = [i], n = 1;    while (i !== e) {      i += step;      result[n++] = i;    }    return result;  };};
    var $dot$dot = range;
    var $bang$bang = function (xs) {
        return function (n) {
            var isInt = function (n_1) {
                return n_1 !== ~~n_1;
            };
            return n < 0 || (n >= length(xs) || isInt(n)) ? Data_Maybe.Nothing.value : new Data_Maybe.Just(xs[n]);
        };
    };
    var singleton = function (a) {
        return [ a ];
    };
    var nubBy = function (_102) {
        return function (_103) {
            if (_103.length === 0) {
                return [  ];
            };
            if (_103.length >= 1) {
                var _365 = _103.slice(1);
                return Prelude[":"](_103[0])(nubBy(_102)(filter(function (y) {
                    return !_102(_103[0])(y);
                })(_365)));
            };
            throw new Error("Failed pattern match");
        };
    };
    var nub = function (__dict_Eq_57) {
        return nubBy(Prelude["=="](__dict_Eq_57));
    };
    var functorArray = new Prelude.Functor(map);
    var monadArray = new Prelude.Monad(function () {
        return applicativeArray;
    }, function () {
        return bindArray;
    });
    var bindArray = new Prelude.Bind(Prelude.flip(concatMap), function () {
        return applyArray;
    });
    var applyArray = new Prelude.Apply(Prelude.ap(monadArray), function () {
        return functorArray;
    });
    var applicativeArray = new Prelude.Applicative(function () {
        return applyArray;
    }, singleton);
    return {
        "!!": $bang$bang, 
        "..": $dot$dot, 
        applicativeArray: applicativeArray, 
        applyArray: applyArray, 
        bindArray: bindArray, 
        concat: concat, 
        concatMap: concatMap, 
        filter: filter, 
        functorArray: functorArray, 
        length: length, 
        map: map, 
        monadArray: monadArray, 
        nub: nub, 
        nubBy: nubBy, 
        range: range, 
        singleton: singleton, 
        snoc: snoc, 
        updateAt: updateAt
    };
})();
var PS = PS || {};
PS.Data_Monoid = (function () {
    "use strict";
    var Prelude = PS.Prelude;
    var mempty = function (dict) {
        return dict.mempty;
    };
    return {
        mempty: mempty
    };
})();
var PS = PS || {};
PS.Data_Foldable = (function () {
    "use strict";
    var Data_Monoid = PS.Data_Monoid;
    var Prelude = PS.Prelude;
    var Control_Apply = PS.Control_Apply;
    var Data_Monoid_First = PS.Data_Monoid_First;
    function Foldable(foldMap, foldl, foldr) {
        this.foldMap = foldMap;
        this.foldl = foldl;
        this.foldr = foldr;
    };
    
  function foldrArray(f) {
    return function(z) {
      return function(xs) {
        var acc = z;
        for (var i = xs.length - 1; i >= 0; --i) {
          acc = f(xs[i])(acc);
        }
        return acc;
      }
    }
  };
    
  function foldlArray(f) {
    return function(z) {
      return function(xs) {
        var acc = z;
        for (var i = 0, len = xs.length; i < len; ++i) {
          acc = f(acc)(xs[i]);
        }
        return acc;
      }
    }
  };
    var foldr = function (dict) {
        return dict.foldr;
    };
    var foldl = function (dict) {
        return dict.foldl;
    };
    var foldableArray = new Foldable(function (__dict_Monoid_112) {
        return function (f) {
            return function (xs) {
                return foldr(foldableArray)(function (x) {
                    return function (acc) {
                        return Prelude["<>"](__dict_Monoid_112["__superclass_Prelude.Semigroup_0"]())(f(x))(acc);
                    };
                })(Data_Monoid.mempty(__dict_Monoid_112))(xs);
            };
        };
    }, function (f) {
        return function (z) {
            return function (xs) {
                return foldlArray(f)(z)(xs);
            };
        };
    }, function (f) {
        return function (z) {
            return function (xs) {
                return foldrArray(f)(z)(xs);
            };
        };
    });
    return {
        Foldable: Foldable, 
        foldableArray: foldableArray, 
        foldl: foldl, 
        foldlArray: foldlArray, 
        foldr: foldr, 
        foldrArray: foldrArray
    };
})();
var PS = PS || {};
PS.Data_Map = (function () {
    "use strict";
    var Prelude = PS.Prelude;
    var Data_Foldable = PS.Data_Foldable;
    var Data_Tuple = PS.Data_Tuple;
    var Data_Traversable = PS.Data_Traversable;
    var Data_Array = PS.Data_Array;
    var Data_Maybe = PS.Data_Maybe;
    function Leaf() {

    };
    Leaf.value = new Leaf();
    function Two(value0, value1, value2, value3) {
        this.value0 = value0;
        this.value1 = value1;
        this.value2 = value2;
        this.value3 = value3;
    };
    Two.create = function (value0) {
        return function (value1) {
            return function (value2) {
                return function (value3) {
                    return new Two(value0, value1, value2, value3);
                };
            };
        };
    };
    function Three(value0, value1, value2, value3, value4, value5, value6) {
        this.value0 = value0;
        this.value1 = value1;
        this.value2 = value2;
        this.value3 = value3;
        this.value4 = value4;
        this.value5 = value5;
        this.value6 = value6;
    };
    Three.create = function (value0) {
        return function (value1) {
            return function (value2) {
                return function (value3) {
                    return function (value4) {
                        return function (value5) {
                            return function (value6) {
                                return new Three(value0, value1, value2, value3, value4, value5, value6);
                            };
                        };
                    };
                };
            };
        };
    };
    function TwoLeft(value0, value1, value2) {
        this.value0 = value0;
        this.value1 = value1;
        this.value2 = value2;
    };
    TwoLeft.create = function (value0) {
        return function (value1) {
            return function (value2) {
                return new TwoLeft(value0, value1, value2);
            };
        };
    };
    function TwoRight(value0, value1, value2) {
        this.value0 = value0;
        this.value1 = value1;
        this.value2 = value2;
    };
    TwoRight.create = function (value0) {
        return function (value1) {
            return function (value2) {
                return new TwoRight(value0, value1, value2);
            };
        };
    };
    function ThreeLeft(value0, value1, value2, value3, value4, value5) {
        this.value0 = value0;
        this.value1 = value1;
        this.value2 = value2;
        this.value3 = value3;
        this.value4 = value4;
        this.value5 = value5;
    };
    ThreeLeft.create = function (value0) {
        return function (value1) {
            return function (value2) {
                return function (value3) {
                    return function (value4) {
                        return function (value5) {
                            return new ThreeLeft(value0, value1, value2, value3, value4, value5);
                        };
                    };
                };
            };
        };
    };
    function ThreeMiddle(value0, value1, value2, value3, value4, value5) {
        this.value0 = value0;
        this.value1 = value1;
        this.value2 = value2;
        this.value3 = value3;
        this.value4 = value4;
        this.value5 = value5;
    };
    ThreeMiddle.create = function (value0) {
        return function (value1) {
            return function (value2) {
                return function (value3) {
                    return function (value4) {
                        return function (value5) {
                            return new ThreeMiddle(value0, value1, value2, value3, value4, value5);
                        };
                    };
                };
            };
        };
    };
    function ThreeRight(value0, value1, value2, value3, value4, value5) {
        this.value0 = value0;
        this.value1 = value1;
        this.value2 = value2;
        this.value3 = value3;
        this.value4 = value4;
        this.value5 = value5;
    };
    ThreeRight.create = function (value0) {
        return function (value1) {
            return function (value2) {
                return function (value3) {
                    return function (value4) {
                        return function (value5) {
                            return new ThreeRight(value0, value1, value2, value3, value4, value5);
                        };
                    };
                };
            };
        };
    };
    function KickUp(value0, value1, value2, value3) {
        this.value0 = value0;
        this.value1 = value1;
        this.value2 = value2;
        this.value3 = value3;
    };
    KickUp.create = function (value0) {
        return function (value1) {
            return function (value2) {
                return function (value3) {
                    return new KickUp(value0, value1, value2, value3);
                };
            };
        };
    };
    var lookup = function (__copy___dict_Ord_147) {
        return function (__copy__272) {
            return function (__copy__273) {
                var __dict_Ord_147 = __copy___dict_Ord_147;
                var _272 = __copy__272;
                var _273 = __copy__273;
                tco: while (true) {
                    if (_273 instanceof Leaf) {
                        return Data_Maybe.Nothing.value;
                    };
                    if (_273 instanceof Two && Prelude["=="](__dict_Ord_147["__superclass_Prelude.Eq_0"]())(_272)(_273.value1)) {
                        return new Data_Maybe.Just(_273.value2);
                    };
                    if (_273 instanceof Two && Prelude["<"](__dict_Ord_147)(_272)(_273.value1)) {
                        var __tco___dict_Ord_147 = __dict_Ord_147;
                        var __tco__272 = _272;
                        var __tco__273 = _273.value0;
                        __dict_Ord_147 = __tco___dict_Ord_147;
                        _272 = __tco__272;
                        _273 = __tco__273;
                        continue tco;
                    };
                    if (_273 instanceof Two) {
                        var __tco___dict_Ord_147 = __dict_Ord_147;
                        var __tco__272 = _272;
                        var __tco__273 = _273.value3;
                        __dict_Ord_147 = __tco___dict_Ord_147;
                        _272 = __tco__272;
                        _273 = __tco__273;
                        continue tco;
                    };
                    if (_273 instanceof Three && Prelude["=="](__dict_Ord_147["__superclass_Prelude.Eq_0"]())(_272)(_273.value1)) {
                        return new Data_Maybe.Just(_273.value2);
                    };
                    if (_273 instanceof Three && Prelude["=="](__dict_Ord_147["__superclass_Prelude.Eq_0"]())(_272)(_273.value4)) {
                        return new Data_Maybe.Just(_273.value5);
                    };
                    if (_273 instanceof Three && Prelude["<"](__dict_Ord_147)(_272)(_273.value1)) {
                        var __tco___dict_Ord_147 = __dict_Ord_147;
                        var __tco__272 = _272;
                        var __tco__273 = _273.value0;
                        __dict_Ord_147 = __tco___dict_Ord_147;
                        _272 = __tco__272;
                        _273 = __tco__273;
                        continue tco;
                    };
                    if (_273 instanceof Three && (Prelude["<"](__dict_Ord_147)(_273.value1)(_272) && Prelude["<="](__dict_Ord_147)(_272)(_273.value4))) {
                        var __tco___dict_Ord_147 = __dict_Ord_147;
                        var __tco__272 = _272;
                        var __tco__273 = _273.value3;
                        __dict_Ord_147 = __tco___dict_Ord_147;
                        _272 = __tco__272;
                        _273 = __tco__273;
                        continue tco;
                    };
                    if (_273 instanceof Three) {
                        var __tco___dict_Ord_147 = __dict_Ord_147;
                        var __tco__272 = _272;
                        var __tco__273 = _273.value6;
                        __dict_Ord_147 = __tco___dict_Ord_147;
                        _272 = __tco__272;
                        _273 = __tco__273;
                        continue tco;
                    };
                    throw new Error("Failed pattern match");
                };
            };
        };
    };
    var member = function (__dict_Ord_148) {
        return function (k) {
            return function (m) {
                return Data_Maybe.isJust(lookup(__dict_Ord_148)(k)(m));
            };
        };
    };
    var fromZipper = function (__copy___dict_Ord_149) {
        return function (__copy__274) {
            return function (__copy__275) {
                var __dict_Ord_149 = __copy___dict_Ord_149;
                var _274 = __copy__274;
                var _275 = __copy__275;
                tco: while (true) {
                    if (_274.length === 0) {
                        return _275;
                    };
                    if (_274.length >= 1) {
                        var _421 = _274.slice(1);
                        if (_274[0] instanceof TwoLeft) {
                            var __tco___dict_Ord_149 = __dict_Ord_149;
                            var __tco__275 = new Two(_275, (_274[0]).value0, (_274[0]).value1, (_274[0]).value2);
                            __dict_Ord_149 = __tco___dict_Ord_149;
                            _274 = _421;
                            _275 = __tco__275;
                            continue tco;
                        };
                    };
                    if (_274.length >= 1) {
                        var _426 = _274.slice(1);
                        if (_274[0] instanceof TwoRight) {
                            var __tco___dict_Ord_149 = __dict_Ord_149;
                            var __tco__275 = new Two((_274[0]).value0, (_274[0]).value1, (_274[0]).value2, _275);
                            __dict_Ord_149 = __tco___dict_Ord_149;
                            _274 = _426;
                            _275 = __tco__275;
                            continue tco;
                        };
                    };
                    if (_274.length >= 1) {
                        var _434 = _274.slice(1);
                        if (_274[0] instanceof ThreeLeft) {
                            var __tco___dict_Ord_149 = __dict_Ord_149;
                            var __tco__275 = new Three(_275, (_274[0]).value0, (_274[0]).value1, (_274[0]).value2, (_274[0]).value3, (_274[0]).value4, (_274[0]).value5);
                            __dict_Ord_149 = __tco___dict_Ord_149;
                            _274 = _434;
                            _275 = __tco__275;
                            continue tco;
                        };
                    };
                    if (_274.length >= 1) {
                        var _442 = _274.slice(1);
                        if (_274[0] instanceof ThreeMiddle) {
                            var __tco___dict_Ord_149 = __dict_Ord_149;
                            var __tco__275 = new Three((_274[0]).value0, (_274[0]).value1, (_274[0]).value2, _275, (_274[0]).value3, (_274[0]).value4, (_274[0]).value5);
                            __dict_Ord_149 = __tco___dict_Ord_149;
                            _274 = _442;
                            _275 = __tco__275;
                            continue tco;
                        };
                    };
                    if (_274.length >= 1) {
                        var _450 = _274.slice(1);
                        if (_274[0] instanceof ThreeRight) {
                            var __tco___dict_Ord_149 = __dict_Ord_149;
                            var __tco__275 = new Three((_274[0]).value0, (_274[0]).value1, (_274[0]).value2, (_274[0]).value3, (_274[0]).value4, (_274[0]).value5, _275);
                            __dict_Ord_149 = __tco___dict_Ord_149;
                            _274 = _450;
                            _275 = __tco__275;
                            continue tco;
                        };
                    };
                    throw new Error("Failed pattern match");
                };
            };
        };
    };
    var insert = function (__dict_Ord_150) {
        var up = function (__copy___dict_Ord_151) {
            return function (__copy__286) {
                return function (__copy__287) {
                    var __dict_Ord_151 = __copy___dict_Ord_151;
                    var _286 = __copy__286;
                    var _287 = __copy__287;
                    tco: while (true) {
                        if (_286.length === 0) {
                            return new Two(_287.value0, _287.value1, _287.value2, _287.value3);
                        };
                        if (_286.length >= 1) {
                            var _465 = _286.slice(1);
                            if (_286[0] instanceof TwoLeft) {
                                return fromZipper(__dict_Ord_151)(_465)(new Three(_287.value0, _287.value1, _287.value2, _287.value3, (_286[0]).value0, (_286[0]).value1, (_286[0]).value2));
                            };
                        };
                        if (_286.length >= 1) {
                            var _474 = _286.slice(1);
                            if (_286[0] instanceof TwoRight) {
                                return fromZipper(__dict_Ord_151)(_474)(new Three((_286[0]).value0, (_286[0]).value1, (_286[0]).value2, _287.value0, _287.value1, _287.value2, _287.value3));
                            };
                        };
                        if (_286.length >= 1) {
                            var _486 = _286.slice(1);
                            if (_286[0] instanceof ThreeLeft) {
                                var __tco___dict_Ord_151 = __dict_Ord_151;
                                var __tco__287 = new KickUp(new Two(_287.value0, _287.value1, _287.value2, _287.value3), (_286[0]).value0, (_286[0]).value1, new Two((_286[0]).value2, (_286[0]).value3, (_286[0]).value4, (_286[0]).value5));
                                __dict_Ord_151 = __tco___dict_Ord_151;
                                _286 = _486;
                                _287 = __tco__287;
                                continue tco;
                            };
                        };
                        if (_286.length >= 1) {
                            var _498 = _286.slice(1);
                            if (_286[0] instanceof ThreeMiddle) {
                                var __tco___dict_Ord_151 = __dict_Ord_151;
                                var __tco__287 = new KickUp(new Two((_286[0]).value0, (_286[0]).value1, (_286[0]).value2, _287.value0), _287.value1, _287.value2, new Two(_287.value3, (_286[0]).value3, (_286[0]).value4, (_286[0]).value5));
                                __dict_Ord_151 = __tco___dict_Ord_151;
                                _286 = _498;
                                _287 = __tco__287;
                                continue tco;
                            };
                        };
                        if (_286.length >= 1) {
                            var _510 = _286.slice(1);
                            if (_286[0] instanceof ThreeRight) {
                                var __tco___dict_Ord_151 = __dict_Ord_151;
                                var __tco__287 = new KickUp(new Two((_286[0]).value0, (_286[0]).value1, (_286[0]).value2, (_286[0]).value3), (_286[0]).value4, (_286[0]).value5, new Two(_287.value0, _287.value1, _287.value2, _287.value3));
                                __dict_Ord_151 = __tco___dict_Ord_151;
                                _286 = _510;
                                _287 = __tco__287;
                                continue tco;
                            };
                        };
                        throw new Error("Failed pattern match");
                    };
                };
            };
        };
        var down = function (__copy___dict_Ord_152) {
            return function (__copy__282) {
                return function (__copy__283) {
                    return function (__copy__284) {
                        return function (__copy__285) {
                            var __dict_Ord_152 = __copy___dict_Ord_152;
                            var _282 = __copy__282;
                            var _283 = __copy__283;
                            var _284 = __copy__284;
                            var _285 = __copy__285;
                            tco: while (true) {
                                if (_285 instanceof Leaf) {
                                    return up(__dict_Ord_152)(_282)(new KickUp(Leaf.value, _283, _284, Leaf.value));
                                };
                                if (_285 instanceof Two && Prelude["=="](__dict_Ord_152["__superclass_Prelude.Eq_0"]())(_283)(_285.value1)) {
                                    return fromZipper(__dict_Ord_152)(_282)(new Two(_285.value0, _283, _284, _285.value3));
                                };
                                if (_285 instanceof Two && Prelude["<"](__dict_Ord_152)(_283)(_285.value1)) {
                                    var __tco___dict_Ord_152 = __dict_Ord_152;
                                    var __tco__282 = Prelude[":"](new TwoLeft(_285.value1, _285.value2, _285.value3))(_282);
                                    var __tco__283 = _283;
                                    var __tco__284 = _284;
                                    var __tco__285 = _285.value0;
                                    __dict_Ord_152 = __tco___dict_Ord_152;
                                    _282 = __tco__282;
                                    _283 = __tco__283;
                                    _284 = __tco__284;
                                    _285 = __tco__285;
                                    continue tco;
                                };
                                if (_285 instanceof Two) {
                                    var __tco___dict_Ord_152 = __dict_Ord_152;
                                    var __tco__282 = Prelude[":"](new TwoRight(_285.value0, _285.value1, _285.value2))(_282);
                                    var __tco__283 = _283;
                                    var __tco__284 = _284;
                                    var __tco__285 = _285.value3;
                                    __dict_Ord_152 = __tco___dict_Ord_152;
                                    _282 = __tco__282;
                                    _283 = __tco__283;
                                    _284 = __tco__284;
                                    _285 = __tco__285;
                                    continue tco;
                                };
                                if (_285 instanceof Three && Prelude["=="](__dict_Ord_152["__superclass_Prelude.Eq_0"]())(_283)(_285.value1)) {
                                    return fromZipper(__dict_Ord_152)(_282)(new Three(_285.value0, _283, _284, _285.value3, _285.value4, _285.value5, _285.value6));
                                };
                                if (_285 instanceof Three && Prelude["=="](__dict_Ord_152["__superclass_Prelude.Eq_0"]())(_283)(_285.value4)) {
                                    return fromZipper(__dict_Ord_152)(_282)(new Three(_285.value0, _285.value1, _285.value2, _285.value3, _283, _284, _285.value6));
                                };
                                if (_285 instanceof Three && Prelude["<"](__dict_Ord_152)(_283)(_285.value1)) {
                                    var __tco___dict_Ord_152 = __dict_Ord_152;
                                    var __tco__282 = Prelude[":"](new ThreeLeft(_285.value1, _285.value2, _285.value3, _285.value4, _285.value5, _285.value6))(_282);
                                    var __tco__283 = _283;
                                    var __tco__284 = _284;
                                    var __tco__285 = _285.value0;
                                    __dict_Ord_152 = __tco___dict_Ord_152;
                                    _282 = __tco__282;
                                    _283 = __tco__283;
                                    _284 = __tco__284;
                                    _285 = __tco__285;
                                    continue tco;
                                };
                                if (_285 instanceof Three && (Prelude["<"](__dict_Ord_152)(_285.value1)(_283) && Prelude["<="](__dict_Ord_152)(_283)(_285.value4))) {
                                    var __tco___dict_Ord_152 = __dict_Ord_152;
                                    var __tco__282 = Prelude[":"](new ThreeMiddle(_285.value0, _285.value1, _285.value2, _285.value4, _285.value5, _285.value6))(_282);
                                    var __tco__283 = _283;
                                    var __tco__284 = _284;
                                    var __tco__285 = _285.value3;
                                    __dict_Ord_152 = __tco___dict_Ord_152;
                                    _282 = __tco__282;
                                    _283 = __tco__283;
                                    _284 = __tco__284;
                                    _285 = __tco__285;
                                    continue tco;
                                };
                                if (_285 instanceof Three) {
                                    var __tco___dict_Ord_152 = __dict_Ord_152;
                                    var __tco__282 = Prelude[":"](new ThreeRight(_285.value0, _285.value1, _285.value2, _285.value3, _285.value4, _285.value5))(_282);
                                    var __tco__283 = _283;
                                    var __tco__284 = _284;
                                    var __tco__285 = _285.value6;
                                    __dict_Ord_152 = __tco___dict_Ord_152;
                                    _282 = __tco__282;
                                    _283 = __tco__283;
                                    _284 = __tco__284;
                                    _285 = __tco__285;
                                    continue tco;
                                };
                                throw new Error("Failed pattern match");
                            };
                        };
                    };
                };
            };
        };
        return down(__dict_Ord_150)([  ]);
    };
    var empty = Leaf.value;
    return {
        empty: empty, 
        insert: insert, 
        lookup: lookup, 
        member: member
    };
})();
var PS = PS || {};
PS.Data_Set = (function () {
    "use strict";
    var Prelude = PS.Prelude;
    var Data_Map = PS.Data_Map;
    var Data_Array = PS.Data_Array;
    var Data_Tuple = PS.Data_Tuple;
    var Data_Foldable = PS.Data_Foldable;
    function Set(value0) {
        this.value0 = value0;
    };
    Set.create = function (value0) {
        return new Set(value0);
    };
    var member = function (__dict_Ord_174) {
        return function (_300) {
            return function (_301) {
                return Data_Map.member(__dict_Ord_174)(_300)(_301.value0);
            };
        };
    };
    var insert = function (__dict_Ord_175) {
        return function (_302) {
            return function (_303) {
                return new Set(Data_Map.insert(__dict_Ord_175)(_302)(Prelude.unit)(_303.value0));
            };
        };
    };
    var empty = new Set(Data_Map.empty);
    var fromList = function (__dict_Ord_177) {
        return Data_Foldable.foldl(Data_Foldable.foldableArray)(function (m) {
            return function (a) {
                return insert(__dict_Ord_177)(a)(m);
            };
        })(empty);
    };
    return {
        empty: empty, 
        fromList: fromList, 
        insert: insert, 
        member: member
    };
})();
var PS = PS || {};
PS.Grid = (function () {
    "use strict";
    var Prelude = PS.Prelude;
    var Data_Array = PS.Data_Array;
    var Data_Foldable = PS.Data_Foldable;
    var Data_Set = PS.Data_Set;
    var Control_Monad_Eff_Random = PS.Control_Monad_Eff_Random;
    var Math = PS.Math;
    var Control_Monad_Eff = PS.Control_Monad_Eff;
    var Data_Maybe = PS.Data_Maybe;
    function Coords(value0, value1) {
        this.value0 = value0;
        this.value1 = value1;
    };
    Coords.create = function (value0) {
        return function (value1) {
            return new Coords(value0, value1);
        };
    };
    function Dimensions(value0, value1) {
        this.value0 = value0;
        this.value1 = value1;
    };
    Dimensions.create = function (value0) {
        return function (value1) {
            return new Dimensions(value0, value1);
        };
    };
    function Mine() {

    };
    Mine.value = new Mine();
    function Hint(value0) {
        this.value0 = value0;
    };
    Hint.create = function (value0) {
        return new Hint(value0);
    };
    function Cell(value0) {
        this.value0 = value0;
    };
    Cell.create = function (value0) {
        return new Cell(value0);
    };
    function Grid(value0) {
        this.value0 = value0;
    };
    Grid.create = function (value0) {
        return new Grid(value0);
    };
    var updateValue = function (_315) {
        return function (_316) {
            return new Cell({
                coords: _315.value0.coords, 
                value: _316
            });
        };
    };
    var sub1 = Prelude.flip(Prelude["-"](Prelude.numNumber))(1);
    var surroundingCoords = function (_329) {
        var coordinateDeltas = [ [ sub1, Prelude.id(Prelude.categoryArr) ], [ Prelude["+"](Prelude.numNumber)(1), Prelude.id(Prelude.categoryArr) ], [ Prelude.id(Prelude.categoryArr), sub1 ], [ Prelude.id(Prelude.categoryArr), Prelude["+"](Prelude.numNumber)(1) ], [ sub1, sub1 ], [ Prelude["+"](Prelude.numNumber)(1), Prelude["+"](Prelude.numNumber)(1) ], [ sub1, Prelude["+"](Prelude.numNumber)(1) ], [ Prelude["+"](Prelude.numNumber)(1), sub1 ] ];
        var applyDeltas = function (_347) {
            if (_347.length === 2) {
                return new Coords(_347[0](_329.value0), _347[1](_329.value1));
            };
            throw new Error("Failed pattern match");
        };
        return Data_Array.map(applyDeltas)(coordinateDeltas);
    };
    var randomInt = function (max) {
        return function __do() {
            var _14 = Control_Monad_Eff_Random.random();
            return 1 + Math.floor(_14 * max);
        };
    };
    var mined = function (_326) {
        if (_326.value0.value instanceof Data_Maybe.Just && _326.value0.value.value0 instanceof Mine) {
            return true;
        };
        return false;
    };
    var minedCells = function (_322) {
        return Data_Array.filter(mined)(_322.value0.cells);
    };
    var unmined = Prelude["<<<"](Prelude.semigroupoidArr)(Prelude.not(Prelude.boolLikeBoolean))(mined);
    var unminedCells = function (_323) {
        return Data_Array.filter(unmined)(_323.value0.cells);
    };
    var eqCoords = new Prelude.Eq(function (coords) {
        return function (coords$prime) {
            return !Prelude["=="](eqCoords)(coords)(coords$prime);
        };
    }, function (_334) {
        return function (_335) {
            return _334.value0 === _335.value0 && _334.value1 === _335.value1;
        };
    });
    var ordCoords = new Prelude.Ord(function () {
        return eqCoords;
    }, function (_336) {
        return function (_337) {
            if (_336.value0 === _337.value0) {
                return Prelude.compare(Prelude.ordNumber)(_336.value1)(_337.value1);
            };
            if (Prelude.otherwise) {
                return Prelude.compare(Prelude.ordNumber)(_336.value0)(_337.value0);
            };
            throw new Error("Failed pattern match");
        };
    });
    var neighbor = function (_324) {
        return function (_325) {
            return Data_Set.member(ordCoords)(_325.value0.coords)(Data_Set.fromList(ordCoords)(surroundingCoords(_324)));
        };
    };
    var surroundingCells = function (_327) {
        return function (_328) {
            return Data_Array.filter(neighbor(_327))(_328.value0.cells);
        };
    };
    var randomCoords = function (_320) {
        return function (_321) {
            var randomCoords$prime = function (_344) {
                return function (_345) {
                    return function (_346) {
                        if (Data_Array.length(_346) === _344) {
                            return Prelude["return"](Control_Monad_Eff.monadEff)(_346);
                        };
                        if (Prelude.otherwise) {
                            return function __do() {
                                var _13 = randomInt(_345.value0)();
                                var _12 = randomInt(_345.value1)();
                                return randomCoords$prime(_344)(_345)(Data_Array.nub(eqCoords)(Data_Array.snoc(_346)(new Coords(_13, _12))))();
                            };
                        };
                        throw new Error("Failed pattern match");
                    };
                };
            };
            return randomCoords$prime(_320)(_321.value0.dimensions)([  ]);
        };
    };
    var emptyCells = function (_314) {
        return Data_Array.concat(Prelude[">>="](Data_Array.bindArray)(Data_Array[".."](1)(_314.value0))(function (_10) {
            return Prelude[">>="](Data_Array.bindArray)(Data_Array[".."](1)(_314.value1))(function (_9) {
                return Prelude["return"](Data_Array.monadArray)([ new Cell({
                    coords: new Coords(_10, _9), 
                    value: Data_Maybe.Nothing.value
                }) ]);
            });
        }));
    };
    var emptyGrid = function (dims) {
        return new Grid({
            dimensions: dims, 
            cells: emptyCells(dims)
        });
    };
    var cellIdx = function (_332) {
        return function (_333) {
            return (_333.value0 - 1) * _332.value1 + _333.value1 - 1;
        };
    };
    var updateCell = function (_317) {
        return function (_318) {
            return function (_319) {
                return new Grid({
                    dimensions: _319.value0.dimensions, 
                    cells: Data_Array.updateAt(cellIdx(_319.value0.dimensions)(_317))(_318)(_319.value0.cells)
                });
            };
        };
    };
    var layMines = function (n) {
        return function (grid) {
            var layMines$prime = function (__copy__338) {
                return function (__copy__339) {
                    var _338 = __copy__338;
                    var _339 = __copy__339;
                    tco: while (true) {
                        if (_339.length >= 1) {
                            var _644 = _339.slice(1);
                            var __tco__338 = updateCell(_339[0])(new Cell({
                                coords: _339[0], 
                                value: new Data_Maybe.Just(Mine.value)
                            }))(_338);
                            _338 = __tco__338;
                            _339 = _644;
                            continue tco;
                        };
                        if (_339.length === 0) {
                            return _338;
                        };
                        throw new Error("Failed pattern match");
                    };
                };
            };
            return function __do() {
                var _11 = randomCoords(n)(grid)();
                return layMines$prime(grid)(_11);
            };
        };
    };
    var placeHints = function (grid) {
        var updateHint = function (_342) {
            return function (_343) {
                if (_343.value0.value instanceof Data_Maybe.Just && _343.value0.value.value0 instanceof Mine) {
                    return _342;
                };
                if (_343.value0.value instanceof Data_Maybe.Nothing) {
                    return updateCell(_343.value0.coords)(updateValue(_343)(new Data_Maybe.Just(new Hint(1))))(_342);
                };
                if (_343.value0.value instanceof Data_Maybe.Just && _343.value0.value.value0 instanceof Hint) {
                    return updateCell(_343.value0.coords)(updateValue(_343)(new Data_Maybe.Just(new Hint(1 + _343.value0.value.value0.value0))))(_342);
                };
                throw new Error("Failed pattern match");
            };
        };
        var updateHints = function (_340) {
            return function (_341) {
                return Data_Foldable.foldl(Data_Foldable.foldableArray)(updateHint)(_340)(surroundingCells(_341.value0.coords)(_340));
            };
        };
        return Data_Foldable.foldl(Data_Foldable.foldableArray)(updateHints)(grid)(minedCells(grid));
    };
    var newGrid = function (dims) {
        return function (mines) {
            return function __do() {
                var _8 = layMines(mines)(emptyGrid(dims))();
                return placeHints(_8);
            };
        };
    };
    var cellAt = function (_330) {
        return function (_331) {
            return Data_Array["!!"](_330.value0.cells)(cellIdx(_330.value0.dimensions)(_331));
        };
    };
    var valueAt = function (grid) {
        return function (coords) {
            var unwrap = function (_350) {
                if (_350 instanceof Data_Maybe.Just) {
                    return _350.value0.value0.value;
                };
                if (_350 instanceof Data_Maybe.Nothing) {
                    return Data_Maybe.Nothing.value;
                };
                throw new Error("Failed pattern match");
            };
            return unwrap(cellAt(grid)(coords));
        };
    };
    var isHintAt = function (grid) {
        return function (coords) {
            var isHintAt$prime = function (_348) {
                if (_348 instanceof Data_Maybe.Just && _348.value0 instanceof Hint) {
                    return true;
                };
                return false;
            };
            return isHintAt$prime(valueAt(grid)(coords));
        };
    };
    var isMineAt = function (grid) {
        return function (coords) {
            var isHintAt$prime = function (_349) {
                if (_349 instanceof Data_Maybe.Just && _349.value0 instanceof Mine) {
                    return true;
                };
                return false;
            };
            return isHintAt$prime(valueAt(grid)(coords));
        };
    };
    return {
        Cell: Cell, 
        Coords: Coords, 
        Dimensions: Dimensions, 
        Grid: Grid, 
        Hint: Hint, 
        Mine: Mine, 
        cellAt: cellAt, 
        cellIdx: cellIdx, 
        emptyCells: emptyCells, 
        emptyGrid: emptyGrid, 
        eqCoords: eqCoords, 
        isHintAt: isHintAt, 
        isMineAt: isMineAt, 
        layMines: layMines, 
        mined: mined, 
        minedCells: minedCells, 
        neighbor: neighbor, 
        newGrid: newGrid, 
        ordCoords: ordCoords, 
        placeHints: placeHints, 
        randomCoords: randomCoords, 
        randomInt: randomInt, 
        sub1: sub1, 
        surroundingCells: surroundingCells, 
        surroundingCoords: surroundingCoords, 
        unmined: unmined, 
        unminedCells: unminedCells, 
        updateCell: updateCell, 
        updateValue: updateValue, 
        valueAt: valueAt
    };
})();
